project:
  type: website
  output-dir: _site

website:
  description: "A blog built with Quarto"
  site-url: https://alexshaoo.github.io
  title: "Alex Shao's Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Programming"
        href: programming/index.qmd
      - text: "Math"
        href: math/index.qmd
      - text: "Miscellaneous"
        href: miscellaneous/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/alexshaoo

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    page-layout: article

